### ISSUE TITLE
http://www.bentobox.io/ doesn't seam to work

### ISSUE THREAD

**Issue by mariozivic** [bento-io/collection#40]
When I open http://www.bentobox.io/, I only receive header with close link just refreshing the page and with About me section. Javascript console says following:

Uncaught SyntaxError: Unexpected identifier content.js:627
ReferenceError: CONTENT is not defined
    at new masterCtrl (http://www.bentobox.io/javascripts/main.js:85:17)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:28:464)
    at Object.instantiate (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:29:80)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:53:80
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:44:136
    at m (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:6:494)
    at i (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:44:1)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:40:86)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:40:103)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js:39:153 angular.min.js:63
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains. ping?client_id=521121077928184&domain=www.bentobox.io&origin=1&redirect_uri…26relation%3Dparent&response_type=token%2Csigned_request%2Ccode&sdk=joey:1

Regards,
Mario

**Comment by richardTowers** [comment]
I think this should be fixed by my pull request in #39.

**Comment by JonHMChan** [comment]
This has been fixed. Some malformed js in the content
